name: pinact

on:
  pull_request:
    paths:
      - '.github/workflows/**'
      - '**/action.yml'
      - '**/action.yaml'

permissions:
  contents: write

concurrency:
  group: pinact-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  pinact:
    if: github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub App token
        id: app-token
        uses: actions/create-github-app-token@29824e69f54612133e76f7eaac726eef6c875baf # v2.2.1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.SECRET_KEY }}

      - name: Checkout
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Pin actions
        uses: suzuki-shunsuke/pinact-action@896d595f299e71d65b9d28349d6956abe144390a # v3.0.0
        with:
          github_token: ${{ steps.app-token.outputs.token }}
